### ISSUE TITLE
CI job trips on Apache Superset 2.x: `AttributeError: module 'flask.json' has no attribute 'JSONEncoder'`

### ISSUE THREAD

**Issue by amotl** [crate/cratedb-examples#313]
## Problem

Invoking `superset db upgrade` fails.

-- https://github.com/crate/cratedb-examples/actions/runs/8005637022/job/21865556761#step:7:290

## History

It failed for the first time on Tue, 20 Feb 2024 03:06:45 GMT. Before, it worked well, and nothing was changed on our ends.

-- https://github.com/crate/cratedb-examples/actions/workflows/application-apache-superset.yml

**Comment by amotl** [comment]
The traceback is:
```python
Traceback (most recent call last):
  File "/path/to/bin/superset", line 5, in <module>
    from superset.cli.main import superset
  File "/path/to/lib/python3.11/site-packages/superset/__init__.py", line 21, in <module>
    from superset.app import create_app
  File "/path/to/lib/python3.11/site-packages/superset/app.py", line 23, in <module>
    from superset.initialization import SupersetAppInitializer
  File "/path/to/lib/python3.11/site-packages/superset/initialization/__init__.py", line 27, in <module>
    from flask_appbuilder import expose, IndexView
  File "/path/to/lib/python3.11/site-packages/flask_appbuilder/__init__.py", line 5, in <module>
    from .api import ModelRestApi  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/lib/python3.11/site-packages/flask_appbuilder/api/__init__.py", line 38, in <module>
    from ..baseviews import AbstractViewApi
  File "/path/to/lib/python3.11/site-packages/flask_appbuilder/baseviews.py", line 22, in <module>
    from .forms import GeneralModelConverter
  File "/path/to/lib/python3.11/site-packages/flask_appbuilder/forms.py", line 3, in <module>
    from flask_wtf import FlaskForm
  File "/path/to/lib/python3.11/site-packages/flask_wtf/__init__.py", line 4, in <module>
    from .recaptcha import Recaptcha
  File "/path/to/lib/python3.11/site-packages/flask_wtf/recaptcha/__init__.py", line 1, in <module>
    from .fields import RecaptchaField
  File "/path/to/lib/python3.11/site-packages/flask_wtf/recaptcha/fields.py", line 3, in <module>
    from . import widgets
  File "/path/to/lib/python3.11/site-packages/flask_wtf/recaptcha/widgets.py", line 6, in <module>
    JSONEncoder = json.JSONEncoder
                  ^^^^^^^^^^^^^^^^
AttributeError: module 'flask.json' has no attribute 'JSONEncoder'
```

**Comment by amotl** [comment]
Downgrading to Flask 2.2, using `pip install 'flask<2.3'`, as suggested, trips with a totally different error:

```
ERROR [flask_migrate] Error: Can't locate revision identified by 'b7851ee5522f'
```

**Comment by amotl** [comment]
Reported to upstream.

- https://github.com/apache/superset/issues/27204

**Comment by amotl** [comment]
The upstream issue has been converted into a discussion, because Apache Superset 2.x is not supported any longer. Thanks, @michael-s-molina.

- https://github.com/apache/superset/discussions/27211

/cc @proddata

**Comment by amotl** [comment]
GH-335 will remove testing of Apache Superset 2.x on CI.
